name: CI
on: [push, pull_request]

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  test:
    defaults:
      run:
        shell: bash
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache-setup
        env:
          # cache-setup use binstall to install sccache,
          # which works better when we provide it with GITHUB_TOKEN.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Rust
        run: |
          rustup toolchain add ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - run: cargo test --all-features

  clippy:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: |
          rustup toolchain add stable --no-self-update --component clippy
          rustup default stable
      - uses: ./.github/actions/cache-setup
        env:
          # cache-setup use binstall to install sccache,
          # which works better when we provide it with GITHUB_TOKEN.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          ./avoid-dev-deps.sh
          cargo clippy --no-deps

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: |
          rustup toolchain add stable --no-self-update --component rustfmt
          rustup default stable
      - run: cargo fmt -- --check
