name: CI
on: [push, pull_request]

env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: "true"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@3
      - name: Install Rust
        run: |
          rustup toolchain ${{ matrix.rust }} nightly --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Generate Cargo.lock
        run: cargo +nightly update
      - name: Configure caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ matrix.os }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test --all-features

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - name: Install Rust
        run: |
          rustup toolchain nightly --no-self-update
          rustup component add rustfmt --toolchain nightly
      - run: cargo +nightly fmt -- --check
