name: test make-4.4
on: [push, pull_request]

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  MAKE_VERSION: "4.4.1"

jobs:
  test:
    name: Test using make 4.4.1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable, beta, nightly]
    defaults:
      run:
        shell: bash
    steps:
      - name: Cache make compiled
        id: cache-make
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/make
          key: ${{ matrix.os }}-make-${{ env.MAKE_VERSION }}

      # Compile it from source (temporarily)
      - name: Make GNU Make from source
        if: steps.cache-make.outputs.cache-hit != 'true'
        run: |
          curl "https://ftp.gnu.org/gnu/make/make-${MAKE_VERSION}.tar.gz" | tar xz
          pushd "make-${MAKE_VERSION}"
          ./configure
          make -j 4
          popd
          cp -rp "make-${MAKE_VERSION}/make" /usr/local/bin

      - name: Verify that we are using make 4.4.1
        run: make -v | grep "GNU Make ${MAKE_VERSION}"

      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup toolchain add ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Create Cargo.lock
        run: cargo update
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features
