name: msrv
on: [push, pull_request]

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  test:
    name: msrv
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: |
          rustup toolchain add 1.58 nightly --no-self-update
          rustup default 1.58
      - uses: ./.github/actions/cache-setup
        env:
          # cache-setup use binstall to install sccache,
          # which works better when we provide it with GITHUB_TOKEN.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          set -euxo pipefail
          # Some dev-dependencies require a newer version of Rust, but it doesn't matter for MSRV check
          # This is a workaround for the cargo nightly option `-Z avoid-dev-deps`
          sed 's/\[dev-dependencies\]/[workaround-avoid-dev-deps]/g' ./Cargo.toml >Cargo.toml.tmp
          mv Cargo.toml.tmp ./Cargo.toml
          cargo check --all-features
