name: msrv
on: [push, pull_request]

env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: "true"

jobs:
  test:
    name: msrv
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: |
          rustup toolchain add 1.54 nightly --no-self-update
          rustup default 1.54
      - name: Generate Cargo.lock
        run: cargo +nightly update
      - name: Configure caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ matrix.os }}-1.52-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo check --all-features
